import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../data/qr_repository.dart';

class QrCodeScreen extends ConsumerWidget {
  const QrCodeScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final qrAsync = ref.watch(qrCodeProvider);

    return Scaffold(
      appBar: AppBar(title: const Text('My QR Code')),
      body: qrAsync.when(
        data: (qrData) {
          if (qrData == null) {
            return Center(
              child: Padding(
                padding: const EdgeInsets.all(32),
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Container(
                      padding: const EdgeInsets.all(20),
                      decoration: BoxDecoration(
                        color: const Color(0xFFF1F5F9),
                        borderRadius: BorderRadius.circular(20),
                      ),
                      child: const Icon(Icons.qr_code_2_rounded,
                          size: 56, color: Color(0xFF94A3B8)),
                    ),
                    const SizedBox(height: 20),
                    const Text(
                      'No QR code available yet',
                      style: TextStyle(
                          fontSize: 18,
                          fontWeight: FontWeight.w700,
                          color: Color(0xFF1E293B)),
                    ),
                    const SizedBox(height: 8),
                    const Text(
                      'Your table QR code will appear here once generated by the admin.',
                      textAlign: TextAlign.center,
                      style: TextStyle(color: Color(0xFF94A3B8), height: 1.5),
                    ),
                  ],
                ),
              ),
            );
          }

          final qrDataUrl = qrData['qrDataUrl'] as String?;
          final qrUrl = qrData['qrUrl'] as String?;
          final tableName = qrData['table']?['number']?.toString() ?? '-';

          return SingleChildScrollView(
            padding: const EdgeInsets.all(24),
            child: Column(
              children: [
                const SizedBox(height: 16),
                Container(
                  width: 260,
                  height: 260,
                  padding: const EdgeInsets.all(20),
                  decoration: BoxDecoration(
                    color: Colors.white,
                    borderRadius: BorderRadius.circular(24),
                    boxShadow: [
                      BoxShadow(
                        color: Colors.black.withValues(alpha: 0.06),
                        blurRadius: 40,
                        offset: const Offset(0, 12),
                      ),
                    ],
                  ),
                  child: qrDataUrl != null
                      ? Image.memory(
                          _extractImageData(qrDataUrl),
                          fit: BoxFit.contain,
                        )
                      : const Center(
                          child: Icon(Icons.qr_code_2_rounded,
                              size: 100, color: Color(0xFFCBD5E1)),
                        ),
                ),
                const SizedBox(height: 24),
                Text(
                  'Table #$tableName',
                  style: const TextStyle(
                    fontSize: 26,
                    fontWeight: FontWeight.w800,
                    color: Color(0xFF1E293B),
                  ),
                ),
                const SizedBox(height: 4),
                const Text(
                  'Show this QR code to your customers',
                  style: TextStyle(color: Color(0xFF94A3B8), fontSize: 14),
                ),
                const SizedBox(height: 28),
                if (qrUrl != null)
                  Container(
                    width: double.infinity,
                    padding: const EdgeInsets.all(14),
                    decoration: BoxDecoration(
                      color: const Color(0xFFF8FAFC),
                      borderRadius: BorderRadius.circular(14),
                      border: Border.all(color: const Color(0xFFF1F5F9)),
                    ),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Row(
                          children: [
                            const Icon(Icons.link_rounded,
                                size: 14, color: Color(0xFF94A3B8)),
                            const SizedBox(width: 6),
                            Text('QR URL',
                                style: TextStyle(
                                    fontSize: 11,
                                    color: Colors.grey.shade500,
                                    fontWeight: FontWeight.w600)),
                          ],
                        ),
                        const SizedBox(height: 6),
                        SelectableText(
                          qrUrl,
                          style: const TextStyle(
                              fontSize: 12,
                              fontFamily: 'monospace',
                              color: Color(0xFF64748B)),
                        ),
                      ],
                    ),
                  ),
                const SizedBox(height: 24),
                SizedBox(
                  width: double.infinity,
                  height: 50,
                  child: ElevatedButton.icon(
                    onPressed: () {
                      if (qrDataUrl != null) {
                        _downloadQrCode(context, qrDataUrl, tableName);
                      }
                    },
                    style: ElevatedButton.styleFrom(
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(14),
                      ),
                    ),
                    icon: const Icon(Icons.download_rounded, size: 20),
                    label: const Text('Download QR Code',
                        style: TextStyle(fontWeight: FontWeight.w600)),
                  ),
                ),
                const SizedBox(height: 12),
                SizedBox(
                  width: double.infinity,
                  height: 50,
                  child: OutlinedButton.icon(
                    onPressed: () {
                      if (qrDataUrl != null) {
                        _shareQrCode(context, qrDataUrl, tableName);
                      }
                    },
                    style: OutlinedButton.styleFrom(
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(14),
                      ),
                    ),
                    icon: const Icon(Icons.share_rounded, size: 20),
                    label: const Text('Share QR Code',
                        style: TextStyle(fontWeight: FontWeight.w600)),
                  ),
                ),
                const SizedBox(height: 24),
                Container(
                  width: double.infinity,
                  padding: const EdgeInsets.all(18),
                  decoration: BoxDecoration(
                    gradient: LinearGradient(
                      colors: [
                        const Color(0xFFF97316).withValues(alpha: 0.08),
                        const Color(0xFFF97316).withValues(alpha: 0.03),
                      ],
                      begin: Alignment.topLeft,
                      end: Alignment.bottomRight,
                    ),
                    borderRadius: BorderRadius.circular(16),
                    border: Border.all(
                      color: const Color(0xFFF97316).withValues(alpha: 0.15),
                    ),
                  ),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Row(
                        children: [
                          Container(
                            padding: const EdgeInsets.all(6),
                            decoration: BoxDecoration(
                              color: const Color(0xFFF97316)
                                  .withValues(alpha: 0.15),
                              borderRadius: BorderRadius.circular(8),
                            ),
                            child: const Icon(Icons.info_outline_rounded,
                                color: Color(0xFFF97316), size: 16),
                          ),
                          const SizedBox(width: 10),
                          Text(
                            'How it works',
                            style: TextStyle(
                              fontWeight: FontWeight.w700,
                              color: Colors.orange.shade700,
                              fontSize: 14,
                            ),
                          ),
                        ],
                      ),
                      const SizedBox(height: 12),
                      Text(
                        '1. Print this QR code and place it on your table\n'
                        '2. Customers scan it with their phone camera\n'
                        '3. They see your menu and can place orders instantly',
                        style: TextStyle(
                          fontSize: 13,
                          color: Colors.orange.shade700,
                          height: 1.7,
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            ),
          );
        },
        loading: () => const Center(child: CircularProgressIndicator()),
        error: (e, _) => Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const Icon(Icons.error_outline_rounded,
                  size: 48, color: Color(0xFFCBD5E1)),
              const SizedBox(height: 16),
              Text('Error loading QR code',
                  style: TextStyle(color: Colors.grey.shade600)),
              const SizedBox(height: 8),
              Text('$e',
                  style:
                      const TextStyle(fontSize: 12, color: Color(0xFF94A3B8))),
            ],
          ),
        ),
      ),
    );
  }

  Uint8List _extractImageData(String dataUrl) {
    final base64Str = dataUrl.split(',').last;
    return Uint8List.fromList(base64Str.codeUnits);
  }

  void _downloadQrCode(BuildContext context, String dataUrl, String tableName) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content:
            Text('Long press the QR image above to save it to your device'),
        action: SnackBarAction(
          label: 'OK',
          onPressed: () {},
        ),
      ),
    );
  }

  void _shareQrCode(BuildContext context, String dataUrl, String tableName) {
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(content: Text('Share feature coming soon')),
    );
  }
}
